import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import AboutMe from './AboutMe'
import Contact from './Contact'
import Hero from './Hero'
import Links from './Links'
import Projects from './Projects'
import Skills from './Skills'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section id="section1">
   
  <Hero />
  <Links />
</section>
<section id="section2">
 <AboutMe />
</section>
<section id="section3">
  <Skills />
</section>
<section id="section4">
  <Projects />
</section>
<section id="section5">
  <Contact />
</section>

    </div>
  )
}
