import Head from 'next/head'
import Image from 'next/image'
import AboutMe from './AboutMe'

import Hero from './Hero'
import Skills from './Skills'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Hero />
    <AboutMe />
 <Skills />
    </div>
  )
}
